namespace Chirograph.Application.Abstractions;

/// <summary>Blob storage for stamped PDFs. Keys are opaque, generated by the application, and never reused.</summary>
public interface IFileStore
{
    /// <exception cref="IOException">A file with this key already exists.</exception>
    Task SaveAsync(string key, ReadOnlyMemory<byte> content, string contentType, CancellationToken cancellationToken = default);

    /// <summary>Opens a stored file for reading, or returns <c>null</c> if there is none.</summary>
    Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken = default);

    Task DeleteAsync(string key, CancellationToken cancellationToken = default);
}
