<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Chirograph.Application\Chirograph.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="PDFsharp" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="DnsClient" />
    <PackageReference Include="MailKit" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Chirograph.UnitTests" />
  </ItemGroup>
</Project>
